framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: { enabled: true }
    http_method_override: false
    session:
        name: pdAdmin
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    validation: { enable_annotations: true }
    form: ~
    fragments: ~
    php_errors:
        log: true
    assets:
        packages:
            upload:
                base_path: "uploads"
            admin:
                base_path: "build/admin"
