##
# Authorization Routing
##
authorization:
    resource: "@PdUserBundle/Resources/config/routing.yaml"

##
# Admin Mailer Routing
##
admin_mailer:
    resource: "@PdMailerBundle/Resources/config/routing.yaml"
    prefix: 'admin'

##
# Admin Widget Routing
##
admin_widget:
    resource: "@PdWidgetBundle/Resources/config/routing.yml"
    prefix: 'admin'

##
# Admin Controller Routing
##
admin:
    resource: ../src/Controller/
    type: annotation
    prefix: 'admin'
    name_prefix: 'admin_'
