imports:
    - { resource: "default_config.yaml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Load Voters
    App\Security\:
        resource: '../src/Security/*'

    # Load Widgets
    App\Widgets\:
        resource: '../src/Widgets/*'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }

    # Exception Listener
    App\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
        arguments:
            $environment: "%kernel.environment%"

    # Switch User Listener
    security.authentication.switchuser_listener:
        class: App\Listener\SwitchUserListener
        public: false
        abstract: true
        arguments: [ "@security.token_storage",
                     "",
                     "@security.user_checker",
                     "",
                     "@security.access.decision_manager",
                     "@?logger",
                     "_switch_user",
                     "ROLE_ALLOWED_TO_SWITCH",
                     "@?event_dispatcher",
                     "ROLE_SWITCHABLE" ]
        tags:
            - { name: monolog.logger, channel: security }

    # Twig Extension
    App\Twig\FormatExtension:
        tags: ['twig.extension']

    #    App\:
    #        resource: '../src/*'
    #        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    App\Controller\:
#        resource: '../src/Controller'
#        tags: ['controller.service_arguments']
